# Generated by Django 3.2.6 on 2021-08-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(choices=[('regular', 'regular'), ('medium', 'medium'), ('large', 'large')], max_length=200)),
                ('toppings', models.CharField(choices=[('chicken', 'chicken'), ('mutton', 'mutton'), ('onion', 'onion'), ('tomato', 'tomato')], max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
